//
// D:/Clustered-Shading/ISPC/kernels_x86.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>

namespace ispc
{
	struct PointLight
	{
		float positionView[3];
		float attenuationBegin;
		float color[3];
		float attenuationEnd;
	};

	struct LightBounds
	{
		int p1[3], p2[3];
	};

	struct Camera
	{
		float proj11;
		float proj22;
		float m_near;
		float m_far;
	};

	struct LightGridDimensions
	{
		int width;
		int height;
		int depth;
	};

	struct Fragment
	{
		int cellIndex;
		int lightIndex;
		uint64_t coverage;
	};


	void CoarseRasterizeLights(PointLight lights[], LightBounds bounds[], int lightCount, Camera camera[], LightGridDimensions dim[]);
	void FineRasterizeLights(PointLight lights[], Fragment fragments[], int fragmentCount, Camera camera[], LightGridDimensions dim[]);
}